// Liste complète des pays reconnus (couverture mondiale, équivalente à ce que Shopify
// autorise pour la livraison/facturation) - utilisée dans le formulaire d'adresse pour
// que Ridia Store fonctionne vraiment comme une boutique internationale.
export const COUNTRIES = [
  'Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Allemagne', 'Andorre', 'Angola',
  'Anguilla', 'Antigua-et-Barbuda', 'Arabie saoudite', 'Argentine', 'Arménie', 'Aruba',
  'Australie', 'Autriche', 'Azerbaïdjan', 'Bahamas', 'Bahreïn', 'Bangladesh', 'Barbade',
  'Belgique', 'Belize', 'Bénin', 'Bermudes', 'Bhoutan', 'Biélorussie', 'Birmanie (Myanmar)',
  'Bolivie', 'Bosnie-Herzégovine', 'Botswana', 'Brésil', 'Brunei', 'Bulgarie',
  'Burkina Faso', 'Burundi', 'Cambodge', 'Cameroun', 'Canada', 'Cap-Vert',
  'République centrafricaine', 'Chili', 'Chine', 'Chypre', 'Colombie', 'Comores', 'Congo-Brazzaville',
  'Congo-Kinshasa (RDC)', 'Corée du Sud', 'Costa Rica', "Côte d'Ivoire", 'Croatie', 'Cuba',
  'Curaçao', 'Danemark', 'Djibouti', 'Dominique', 'Égypte', 'Émirats arabes unis', 'Équateur',
  'Érythrée', 'Espagne', 'Estonie', 'Eswatini (Swaziland)', 'États-Unis', 'Éthiopie', 'Fidji',
  'Finlande', 'France', 'Gabon', 'Gambie', 'Géorgie', 'Ghana', 'Gibraltar', 'Grèce', 'Grenade',
  'Groenland', 'Guadeloupe', 'Guatemala', 'Guernesey', 'Guinée', 'Guinée-Bissau',
  'Guinée équatoriale', 'Guyana', 'Guyane française', 'Haïti', 'Honduras', 'Hong Kong',
  'Hongrie', 'Île de Man', 'Îles Caïmans', 'Îles Féroé', 'Îles Falkland', 'Îles Marshall',
  'Îles Salomon', 'Îles Turques-et-Caïques', 'Îles Vierges britanniques', 'Inde', 'Indonésie',
  'Irak', 'Iran', 'Irlande', 'Islande', 'Israël', 'Italie', 'Jamaïque', 'Japon', 'Jersey',
  'Jordanie', 'Kazakhstan', 'Kenya', 'Kirghizistan', 'Kiribati', 'Kosovo', 'Koweït', 'Laos',
  'Lesotho', 'Lettonie', 'Liban', 'Liberia', 'Libye', 'Liechtenstein', 'Lituanie', 'Luxembourg',
  'Macao', 'Macédoine du Nord', 'Madagascar', 'Malaisie', 'Malawi', 'Maldives', 'Mali', 'Malte',
  'Maroc', 'Martinique', 'Maurice', 'Mauritanie', 'Mayotte', 'Mexique', 'Micronésie',
  'Moldavie', 'Monaco', 'Mongolie', 'Monténégro', 'Montserrat', 'Mozambique', 'Namibie',
  'Nauru', 'Népal', 'Nicaragua', 'Niger', 'Nigeria', 'Norvège', 'Nouvelle-Calédonie',
  'Nouvelle-Zélande', 'Oman', 'Ouganda', 'Ouzbékistan', 'Pakistan', 'Palaos',
  'Palestine', 'Panama', 'Papouasie-Nouvelle-Guinée', 'Paraguay', 'Pays-Bas', 'Pérou',
  'Philippines', 'Pologne', 'Polynésie française', 'Porto Rico', 'Portugal', 'Qatar',
  'République dominicaine', 'République tchèque', 'Réunion', 'Roumanie', 'Royaume-Uni',
  'Russie', 'Rwanda', 'Sahara occidental', 'Saint-Christophe-et-Niévès', 'Saint-Marin',
  'Saint-Vincent-et-les-Grenadines', 'Sainte-Lucie', 'Salvador', 'Samoa', 'Sao Tomé-et-Principe',
  'Sénégal', 'Serbie', 'Seychelles', 'Sierra Leone', 'Singapour', 'Slovaquie', 'Slovénie',
  'Somalie', 'Soudan', 'Soudan du Sud', 'Sri Lanka', 'Suède', 'Suisse', 'Suriname', 'Syrie',
  'Tadjikistan', 'Taïwan', 'Tanzanie', 'Tchad', 'Thaïlande', 'Timor oriental', 'Togo', 'Tonga',
  'Trinité-et-Tobago', 'Tunisie', 'Turkménistan', 'Turquie', 'Tuvalu', 'Ukraine', 'Uruguay',
  'Vanuatu', 'Vatican', 'Venezuela', 'Viêt Nam', 'Yémen', 'Zambie', 'Zimbabwe',
] as const;
